trigger:
- yml

pool:
  vmImage: ubuntu-latest

steps:
- script: ip addr show
  displayName: 'Mostrar IP (solo Linux)'

- script: echo $(Build.SourceBranch)
  displayName: 'Verificar rama'

- checkout: self
  displayName: 'Checkout c칩digo'

- script: mvn --version
  displayName: 'Mostrar versi칩n de Maven'

- script: |
    cd KtJenkins
    mvn clean package
    java -cp target/KtJenkins-1.0-SNAPSHOT.jar com.KtJenkins.app.App > ../Reports.txt
  displayName: 'Build y ejecutar App'

- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'SonarQubeServiceConnection' # Cambia por el nombre de tu conexi칩n de servicio
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'Mvn'
    cliProjectName: 'Mvn'

- script: |
    cd KtJenkins
    mvn verify sonar:sonar -Dsonar.projectKey=Mvn -Dsonar.projectName='Mvn'
  displayName: 'An치lisis SonarQube'

- publish: Reports.txt
  artifact: Reports
  displayName: 'Publicar Reports.txt como artefacto'
