name: CI Pipeline

on:
  push:
    branches:
      - main
      - LinuxKt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar Maven
        uses: stCarolas/setup-maven@v4

      - name: Compilar y testear
        run: mvn clean package

      - name: Publicar artefactos
        uses: actions/upload-artifact@v4
        with:
          name: Reports
          path: Reports.txt